// lib/fleet.ts

export interface CarEntry {
  id: string;
  no: string;
  name: string;
  brand: string;
  model: string;
  category: "Luxe" | "Sport" | "Économique";
  categoryColor: string;
  price: number;
  seats: number;
  transmission: string;
  fuel: string;
  power: string;
  description: string;
  features: string[];
  image: string;
}

export const ALL_CARS: CarEntry[] = [
  // ==================== LUXE (6 cars) ====================
  {
    id: "porsche-macan",
    no: "01",
    name: "Porsche Macan",
    brand: "PORSCHE",
    model: "Macan",
    category: "Luxe",
    categoryColor: "#D4AF37",
    price: 1850,
    seats: 5,
    transmission: "Automatique",
    fuel: "Essence",
    power: "265 ch",
    description: "Le SUV sport de Porsche — performance et luxe au rendez-vous. Une expérience de conduite unique à Tanger.",
    features: ["GPS & Cuir pleine fleur", "Caméra 360°", "Toit panoramique", "Assurance incluse"],
    image: "/images/cars/porsche-macan.jpg",
  },
  {
    id: "range-rover-evoque",
    no: "02",
    name: "Range Rover Evoque",
    brand: "RANGE ROVER",
    model: "Evoque",
    category: "Luxe",
    categoryColor: "#D4AF37",
    price: 1450,
    seats: 5,
    transmission: "Automatique",
    fuel: "Diesel",
    power: "240 ch",
    description: "Élégance britannique et technologie de pointe. L'Evoque redéfinit le luxe urbain.",
    features: ["Toit panoramique", "Meridian Audio", "4x4 Terrain Response", "Assurance incluse"],
    image: "/images/cars/range-rover-evoque.jpg",
  },
  {
    id: "mercedes-amg",
    no: "03",
    name: "Mercedes C AMG",
    brand: "MERCEDES",
    model: "C AMG",
    category: "Luxe",
    categoryColor: "#D4AF37",
    price: 1250,
    seats: 5,
    transmission: "Automatique",
    fuel: "Essence",
    power: "435 ch",
    description: "La berline sport par excellence. Puissance brute et sophistication absolue réunies.",
    features: ["AMG Performance Pack", "Burmester Audio", "Sièges sport chauffants", "Assurance incluse"],
    image: "/images/cars/mercedes-amg.jpg",
  },
  {
    id: "audi-a5",
    no: "04",
    name: "Audi A5",
    brand: "AUDI",
    model: "A5 Sportback",
    category: "Luxe",
    categoryColor: "#D4AF37",
    price: 1100,
    seats: 5,
    transmission: "Automatique",
    fuel: "Essence",
    power: "204 ch",
    description: "Coupé sportback d'Audi — design épuré, finition premium et cockpit virtuel.",
    features: ["Virtual Cockpit", "Bang & Olufsen", "Matrix LED", "Assurance incluse"],
    image: "/images/cars/audi-a5.jpg",
  },
  {
    id: "mercedes-class-a",
    no: "12",
    name: "Mercedes Classe A",
    brand: "MERCEDES",
    model: "Classe A",
    category: "Luxe",
    categoryColor: "#D4AF37",
    price: 850,
    seats: 5,
    transmission: "Automatique",
    fuel: "Essence",
    power: "163 ch",
    description: "La compacte premium de Mercedes — technologie MBUX et style irréprochable.",
    features: ["MBUX Infotainment", "Ambient Light 64 couleurs", "Aide au stationnement", "Assurance incluse"],
    image: "/images/cars/mercedes-class-a.jpg",
  },
  {
    id: "vw-touareg",
    no: "06",
    name: "Volkswagen Touareg",
    brand: "VOLKSWAGEN",
    model: "Touareg",
    category: "Luxe",
    categoryColor: "#D4AF37",
    price: 1350,
    seats: 5,
    transmission: "Automatique",
    fuel: "Diesel",
    power: "286 ch",
    description: "Le SUV premium de Volkswagen — spacieux et puissant pour les longs trajets.",
    features: ["4MOTION AWD", "Toit panoramique", "Dynaudio Audio", "Assurance incluse"],
    image: "/images/cars/vw-touareg.jpg",
  },

  // ==================== SPORT (2 cars) ====================
  {
    id: "cupra-formentor",
    no: "05",
    name: "Cupra Formentor",
    brand: "CUPRA",
    model: "Formentor",
    category: "Sport",
    categoryColor: "#FF6B00",
    price: 950,
    seats: 5,
    transmission: "Automatique",
    fuel: "Essence",
    power: "310 ch",
    description: "La surprise sportive de la flotte. Sensations pures et look audacieux.",
    features: ["310 ch", "DSG 7 rapports", "Mode Sport+", "Assurance incluse"],
    image: "/images/cars/cupra-formentor.jpg",
  },

  // ==================== ÉCONOMIQUE (7 cars) ====================
  {
    id: "hyundai-tucson",
    no: "07",
    name: "Hyundai Tucson",
    brand: "HYUNDAI",
    model: "Tucson",
    category: "Économique",
    categoryColor: "#94A3B8",
    price: 650,
    seats: 5,
    transmission: "Automatique",
    fuel: "Essence",
    power: "180 ch",
    description: "Le SUV moderne et bien équipé — confort, sécurité et polyvalence.",
    features: ["Écran 10.25\"", "Apple CarPlay", "ADAS complet", "Assurance incluse"],
    image: "/images/cars/hyundai-tucson.jpg",
  },
  {
    id: "vw-golf-8",
    no: "08",
    name: "Volkswagen Golf 8",
    brand: "VOLKSWAGEN",
    model: "Golf 8",
    category: "Économique",
    categoryColor: "#94A3B8",
    price: 550,
    seats: 5,
    transmission: "Automatique",
    fuel: "Essence",
    power: "150 ch",
    description: "La référence des berlines compactes — maniable, économique et fiable.",
    features: ["IQ.Drive", "Digital Cockpit Pro", "Lane Assist", "Assurance incluse"],
    image: "/images/cars/vw-golf-8.jpg",
  },
  {
    id: "dacia-duster",
    no: "09",
    name: "Dacia Duster",
    brand: "DACIA",
    model: "Duster",
    category: "Économique",
    categoryColor: "#94A3B8",
    price: 420,
    seats: 5,
    transmission: "Manuelle",
    fuel: "Diesel",
    power: "115 ch",
    description: "Le SUV robuste et accessible — parfait pour explorer les routes du Maroc.",
    features: ["4x4 disponible", "Climatisation auto", "Grand coffre", "Assurance incluse"],
    image: "/images/cars/dacia-duster.jpg",
  },
  {
    id: "clio-5",
    no: "10",
    name: "Renault Clio 5",
    brand: "RENAULT",
    model: "Clio 5",
    category: "Économique",
    categoryColor: "#94A3B8",
    price: 299,
    seats: 5,
    transmission: "Manuelle",
    fuel: "Essence",
    power: "100 ch",
    description: "La citadine par excellence — économique, pratique et idéale en ville.",
    features: ["Écran tactile", "Bluetooth", "Caméra recul", "Assurance incluse"],
    image: "/images/cars/clio-5.jpg",
  },
  {
    id: "hyundai-creta",
    no: "11",
    name: "Hyundai Creta",
    brand: "HYUNDAI",
    model: "Creta",
    category: "Économique",
    categoryColor: "#94A3B8",
    price: 480,
    seats: 5,
    transmission: "Automatique",
    fuel: "Essence",
    power: "120 ch",
    description: "Le SUV compact moderne — design soigné et confort au quotidien.",
    features: ["Écran 8\"", "Apple CarPlay", "Climatisation", "Assurance incluse"],
    image: "/images/cars/hyundai-creta.jpg",
  },
  {
    id: "vw-t-roc",
    no: "13",
    name: "Volkswagen T-Roc",
    brand: "VOLKSWAGEN",
    model: "T-Roc",
    category: "Économique",
    categoryColor: "#94A3B8",
    price: 590,
    seats: 5,
    transmission: "Automatique",
    fuel: "Essence",
    power: "150 ch",
    description: "Le SUV compact de VW — polyvalent, moderne et bien équipé.",
    features: ["Digital Cockpit", "App Connect", "DCC Adaptive", "Assurance incluse"],
    image: "/images/cars/vw-t-roc.jpg",
  },
  {
    id: "dacia-logan-2024",
    no: "14",
    name: "Dacia Logan 2024",
    brand: "DACIA",
    model: "Logan 2024",
    category: "Économique",
    categoryColor: "#94A3B8",
    price: 250,
    seats: 5,
    transmission: "Manuelle",
    fuel: "Essence",
    power: "90 ch",
    description: "La berline économique la plus fiable — idéale pour les petits budgets.",
    features: ["Grand coffre 528L", "Climatisation", "Bluetooth", "Assurance incluse"],
    image: "/images/cars/dacia-logan-2024.jpg",
  },
  {
    id: "peugeot-208",
    no: "15",
    name: "Peugeot 208",
    brand: "PEUGEOT",
    model: "208",
    category: "Économique",
    categoryColor: "#94A3B8",
    price: 320,
    seats: 5,
    transmission: "Manuelle",
    fuel: "Essence",
    power: "100 ch",
    description: "La citadine française au design primé — élégante, agile et moderne.",
    features: ["i-Cockpit 3D", "Caméra recul", "Carplay/Android", "Assurance incluse"],
    image: "/images/cars/peugeot-208.jpg",
  },
];

/* Featured 4 shown on home page */
export const FEATURED_CARS = ALL_CARS.slice(0, 4);

/* WhatsApp URL helper */
export const waUrl = (car: CarEntry) =>
  `https://wa.me/212661813344?text=${encodeURIComponent(
    `Bonjour, je veux réserver la ${car.name} à Tanger`
  )}`;